<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CountryCode;

class CountryCodeSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'dial_code' => '93', 'iso2' => 'AF'],
            ['country_name' => 'Albania', 'dial_code' => '355', 'iso2' => 'AL'],
            ['country_name' => 'Algeria', 'dial_code' => '213', 'iso2' => 'DZ'],
            ['country_name' => 'American Samoa', 'dial_code' => '1684', 'iso2' => 'AS'],
            ['country_name' => 'Andorra', 'dial_code' => '376', 'iso2' => 'AD'],
            ['country_name' => 'Angola', 'dial_code' => '244', 'iso2' => 'AO'],
            ['country_name' => 'Anguilla', 'dial_code' => '1264', 'iso2' => 'AI'],
            ['country_name' => 'Antigua and Barbuda', 'dial_code' => '1268', 'iso2' => 'AG'],
            ['country_name' => 'Argentina', 'dial_code' => '54', 'iso2' => 'AR'],
            ['country_name' => 'Armenia', 'dial_code' => '374', 'iso2' => 'AM'],
            ['country_name' => 'Aruba', 'dial_code' => '297', 'iso2' => 'AW'],
            ['country_name' => 'Ascension', 'dial_code' => '247', 'iso2' => 'AC'],
            ['country_name' => 'Australia', 'dial_code' => '61', 'iso2' => 'AU'],
            ['country_name' => 'Austria', 'dial_code' => '43', 'iso2' => 'AT'],
            ['country_name' => 'Azerbaijan', 'dial_code' => '994', 'iso2' => 'AZ'],
            ['country_name' => 'Bahamas', 'dial_code' => '1242', 'iso2' => 'BS'],
            ['country_name' => 'Bahrain', 'dial_code' => '973', 'iso2' => 'BH'],
            ['country_name' => 'Bangladesh', 'dial_code' => '880', 'iso2' => 'BD'],
            ['country_name' => 'Barbados', 'dial_code' => '1246', 'iso2' => 'BB'],
            ['country_name' => 'Belarus', 'dial_code' => '375', 'iso2' => 'BY'],
            ['country_name' => 'Belgium', 'dial_code' => '32', 'iso2' => 'BE'],
            ['country_name' => 'Belize', 'dial_code' => '501', 'iso2' => 'BZ'],
            ['country_name' => 'Benin', 'dial_code' => '229', 'iso2' => 'BJ'],
            ['country_name' => 'Bermuda', 'dial_code' => '1441', 'iso2' => 'BM'],
            ['country_name' => 'Bhutan', 'dial_code' => '975', 'iso2' => 'BT'],
            ['country_name' => 'Bolivia', 'dial_code' => '591', 'iso2' => 'BO'],
            ['country_name' => 'Bosnia and Herzegovina', 'dial_code' => '387', 'iso2' => 'BA'],
            ['country_name' => 'Botswana', 'dial_code' => '267', 'iso2' => 'BW'],
            ['country_name' => 'Brazil', 'dial_code' => '55', 'iso2' => 'BR'],
            ['country_name' => 'British Indian Ocean Territory', 'dial_code' => '246', 'iso2' => 'IO'],
            ['country_name' => 'British Virgin Islands', 'dial_code' => '1284', 'iso2' => 'VG'],
            ['country_name' => 'Brunei', 'dial_code' => '673', 'iso2' => 'BN'],
            ['country_name' => 'Bulgaria', 'dial_code' => '359', 'iso2' => 'BG'],
            ['country_name' => 'Burkina Faso', 'dial_code' => '226', 'iso2' => 'BF'],
            ['country_name' => 'Burundi', 'dial_code' => '257', 'iso2' => 'BI'],
            ['country_name' => 'Cambodia', 'dial_code' => '855', 'iso2' => 'KH'],
            ['country_name' => 'Cameroon', 'dial_code' => '237', 'iso2' => 'CM'],
            ['country_name' => 'Canada', 'dial_code' => '1', 'iso2' => 'CA'],
            ['country_name' => 'Cape Verde', 'dial_code' => '238', 'iso2' => 'CV'],
            ['country_name' => 'Cayman Islands', 'dial_code' => '1345', 'iso2' => 'KY'],
            ['country_name' => 'Central African Republic', 'dial_code' => '236', 'iso2' => 'CF'],
            ['country_name' => 'Chad', 'dial_code' => '235', 'iso2' => 'TD'],
            ['country_name' => 'Chile', 'dial_code' => '56', 'iso2' => 'CL'],
            ['country_name' => 'China', 'dial_code' => '86', 'iso2' => 'CN'],
            ['country_name' => 'Christmas Island', 'dial_code' => '6189164', 'iso2' => 'CX'],
            ['country_name' => 'Cocos Islands', 'dial_code' => '6189162', 'iso2' => 'CC'],
            ['country_name' => 'Colombia', 'dial_code' => '57', 'iso2' => 'CO'],
            ['country_name' => 'Comoros', 'dial_code' => '269', 'iso2' => 'KM'],
            ['country_name' => 'Congo', 'dial_code' => '242', 'iso2' => 'CG'],
            ['country_name' => 'Congo, Democratic Republic', 'dial_code' => '243', 'iso2' => 'CD'],
            ['country_name' => 'Cook Islands', 'dial_code' => '682', 'iso2' => 'CK'],
            ['country_name' => 'Costa Rica', 'dial_code' => '506', 'iso2' => 'CR'],
            ['country_name' => 'Croatia', 'dial_code' => '385', 'iso2' => 'HR'],
            ['country_name' => 'Cuba', 'dial_code' => '53', 'iso2' => 'CU'],
            ['country_name' => 'Curacao', 'dial_code' => '5999', 'iso2' => 'CW'],
            ['country_name' => 'Cyprus', 'dial_code' => '357', 'iso2' => 'CY'],
            ['country_name' => 'Czech Republic', 'dial_code' => '420', 'iso2' => 'CZ'],
            ['country_name' => 'Denmark', 'dial_code' => '45', 'iso2' => 'DK'],
            ['country_name' => 'Djibouti', 'dial_code' => '253', 'iso2' => 'DJ'],
            ['country_name' => 'Dominica', 'dial_code' => '1767', 'iso2' => 'DM'],
            ['country_name' => 'Dominican Republic', 'dial_code' => '1809', 'iso2' => 'DO'],
            ['country_name' => 'Ecuador', 'dial_code' => '593', 'iso2' => 'EC'],
            ['country_name' => 'Egypt', 'dial_code' => '20', 'iso2' => 'EG'],
            ['country_name' => 'El Salvador', 'dial_code' => '503', 'iso2' => 'SV'],
            ['country_name' => 'Equatorial Guinea', 'dial_code' => '240', 'iso2' => 'GQ'],
            ['country_name' => 'Eritrea', 'dial_code' => '291', 'iso2' => 'ER'],
            ['country_name' => 'Estonia', 'dial_code' => '372', 'iso2' => 'EE'],
            ['country_name' => 'Eswatini', 'dial_code' => '268', 'iso2' => 'SZ'],
            ['country_name' => 'Ethiopia', 'dial_code' => '251', 'iso2' => 'ET'],
            ['country_name' => 'Falkland Islands', 'dial_code' => '500', 'iso2' => 'FK'],
            ['country_name' => 'Faroe Islands', 'dial_code' => '298', 'iso2' => 'FO'],
            ['country_name' => 'Fiji', 'dial_code' => '679', 'iso2' => 'FJ'],
            ['country_name' => 'Finland', 'dial_code' => '358', 'iso2' => 'FI'],
            ['country_name' => 'France', 'dial_code' => '33', 'iso2' => 'FR'],
            ['country_name' => 'French Guiana', 'dial_code' => '594', 'iso2' => 'GF'],
            ['country_name' => 'French Polynesia', 'dial_code' => '689', 'iso2' => 'PF'],
            ['country_name' => 'Gabon', 'dial_code' => '241', 'iso2' => 'GA'],
            ['country_name' => 'Gambia', 'dial_code' => '220', 'iso2' => 'GM'],
            ['country_name' => 'Georgia', 'dial_code' => '995', 'iso2' => 'GE'],
            ['country_name' => 'Germany', 'dial_code' => '49', 'iso2' => 'DE'],
            ['country_name' => 'Ghana', 'dial_code' => '233', 'iso2' => 'GH'],
            ['country_name' => 'Gibraltar', 'dial_code' => '350', 'iso2' => 'GI'],
            ['country_name' => 'Greece', 'dial_code' => '30', 'iso2' => 'GR'],
            ['country_name' => 'Greenland', 'dial_code' => '299', 'iso2' => 'GL'],
            ['country_name' => 'Grenada', 'dial_code' => '1473', 'iso2' => 'GD'],
            ['country_name' => 'Guadeloupe', 'dial_code' => '590', 'iso2' => 'GP'],
            ['country_name' => 'Guam', 'dial_code' => '1671', 'iso2' => 'GU'],
            ['country_name' => 'Guatemala', 'dial_code' => '502', 'iso2' => 'GT'],
            ['country_name' => 'Guernsey', 'dial_code' => '441481', 'iso2' => 'GG'],
            ['country_name' => 'Guinea', 'dial_code' => '224', 'iso2' => 'GN'],
            ['country_name' => 'Guinea-Bissau', 'dial_code' => '245', 'iso2' => 'GW'],
            ['country_name' => 'Guyana', 'dial_code' => '592', 'iso2' => 'GY'],
            ['country_name' => 'Haiti', 'dial_code' => '509', 'iso2' => 'HT'],
            ['country_name' => 'Honduras', 'dial_code' => '504', 'iso2' => 'HN'],
            ['country_name' => 'Hong Kong', 'dial_code' => '852', 'iso2' => 'HK'],
            ['country_name' => 'Hungary', 'dial_code' => '36', 'iso2' => 'HU'],
            ['country_name' => 'Iceland', 'dial_code' => '354', 'iso2' => 'IS'],
            ['country_name' => 'India', 'dial_code' => '91', 'iso2' => 'IN'],
            ['country_name' => 'Indonesia', 'dial_code' => '62', 'iso2' => 'ID'],
            ['country_name' => 'Iran', 'dial_code' => '98', 'iso2' => 'IR'],
            ['country_name' => 'Iraq', 'dial_code' => '964', 'iso2' => 'IQ'],
            ['country_name' => 'Ireland', 'dial_code' => '353', 'iso2' => 'IE'],
            ['country_name' => 'Isle of Man', 'dial_code' => '441624', 'iso2' => 'IM'],
            ['country_name' => 'Israel', 'dial_code' => '972', 'iso2' => 'IL'],
            ['country_name' => 'Italy', 'dial_code' => '39', 'iso2' => 'IT'],
            ['country_name' => 'Ivory Coast', 'dial_code' => '225', 'iso2' => 'CI'],
            ['country_name' => 'Jamaica', 'dial_code' => '1876', 'iso2' => 'JM'],
            ['country_name' => 'Japan', 'dial_code' => '81', 'iso2' => 'JP'],
            ['country_name' => 'Jersey', 'dial_code' => '441534', 'iso2' => 'JE'],
            ['country_name' => 'Jordan', 'dial_code' => '962', 'iso2' => 'JO'],
            ['country_name' => 'Kazakhstan', 'dial_code' => '76', 'iso2' => 'KZ'],
            ['country_name' => 'Kenya', 'dial_code' => '254', 'iso2' => 'KE'],
            ['country_name' => 'Kiribati', 'dial_code' => '686', 'iso2' => 'KI'],
            ['country_name' => 'Kosovo', 'dial_code' => '383', 'iso2' => 'XK'],
            ['country_name' => 'Kuwait', 'dial_code' => '965', 'iso2' => 'KW'],
            ['country_name' => 'Kyrgyzstan', 'dial_code' => '996', 'iso2' => 'KG'],
            ['country_name' => 'Laos', 'dial_code' => '856', 'iso2' => 'LA'],
            ['country_name' => 'Latvia', 'dial_code' => '371', 'iso2' => 'LV'],
            ['country_name' => 'Lebanon', 'dial_code' => '961', 'iso2' => 'LB'],
            ['country_name' => 'Lesotho', 'dial_code' => '266', 'iso2' => 'LS'],
            ['country_name' => 'Liberia', 'dial_code' => '231', 'iso2' => 'LR'],
            ['country_name' => 'Libya', 'dial_code' => '218', 'iso2' => 'LY'],
            ['country_name' => 'Liechtenstein', 'dial_code' => '423', 'iso2' => 'LI'],
            ['country_name' => 'Lithuania', 'dial_code' => '370', 'iso2' => 'LT'],
            ['country_name' => 'Luxembourg', 'dial_code' => '352', 'iso2' => 'LU'],
            ['country_name' => 'Macau', 'dial_code' => '853', 'iso2' => 'MO'],
            ['country_name' => 'Madagascar', 'dial_code' => '261', 'iso2' => 'MG'],
            ['country_name' => 'Malawi', 'dial_code' => '265', 'iso2' => 'MW'],
            ['country_name' => 'Malaysia', 'dial_code' => '60', 'iso2' => 'MY'],
            ['country_name' => 'Maldives', 'dial_code' => '960', 'iso2' => 'MV'],
            ['country_name' => 'Mali', 'dial_code' => '223', 'iso2' => 'ML'],
            ['country_name' => 'Malta', 'dial_code' => '356', 'iso2' => 'MT'],
            ['country_name' => 'Marshall Islands', 'dial_code' => '692', 'iso2' => 'MH'],
            ['country_name' => 'Martinique', 'dial_code' => '596', 'iso2' => 'MQ'],
            ['country_name' => 'Mauritania', 'dial_code' => '222', 'iso2' => 'MR'],
            ['country_name' => 'Mauritius', 'dial_code' => '230', 'iso2' => 'MU'],
            ['country_name' => 'Mayotte', 'dial_code' => '262269', 'iso2' => 'YT'],
            ['country_name' => 'Mexico', 'dial_code' => '52', 'iso2' => 'MX'],
            ['country_name' => 'Micronesia', 'dial_code' => '691', 'iso2' => 'FM'],
            ['country_name' => 'Moldova', 'dial_code' => '373', 'iso2' => 'MD'],
            ['country_name' => 'Monaco', 'dial_code' => '377', 'iso2' => 'MC'],
            ['country_name' => 'Mongolia', 'dial_code' => '976', 'iso2' => 'MN'],
            ['country_name' => 'Montenegro', 'dial_code' => '382', 'iso2' => 'ME'],
            ['country_name' => 'Montserrat', 'dial_code' => '1664', 'iso2' => 'MS'],
            ['country_name' => 'Morocco', 'dial_code' => '212', 'iso2' => 'MA'],
            ['country_name' => 'Mozambique', 'dial_code' => '258', 'iso2' => 'MZ'],
            ['country_name' => 'Myanmar', 'dial_code' => '95', 'iso2' => 'MM'],
            ['country_name' => 'Namibia', 'dial_code' => '264', 'iso2' => 'NA'],
            ['country_name' => 'Nauru', 'dial_code' => '674', 'iso2' => 'NR'],
            ['country_name' => 'Nepal', 'dial_code' => '977', 'iso2' => 'NP'],
            ['country_name' => 'Netherlands', 'dial_code' => '31', 'iso2' => 'NL'],
            ['country_name' => 'New Caledonia', 'dial_code' => '687', 'iso2' => 'NC'],
            ['country_name' => 'New Zealand', 'dial_code' => '64', 'iso2' => 'NZ'],
            ['country_name' => 'Nicaragua', 'dial_code' => '505', 'iso2' => 'NI'],
            ['country_name' => 'Niger', 'dial_code' => '227', 'iso2' => 'NE'],
            ['country_name' => 'Nigeria', 'dial_code' => '234', 'iso2' => 'NG'],
            ['country_name' => 'Niue', 'dial_code' => '683', 'iso2' => 'NU'],
            ['country_name' => 'Norfolk Island', 'dial_code' => '6723', 'iso2' => 'NF'],
            ['country_name' => 'North Korea', 'dial_code' => '850', 'iso2' => 'KP'],
            ['country_name' => 'North Macedonia', 'dial_code' => '389', 'iso2' => 'MK'],
            ['country_name' => 'Northern Mariana Islands', 'dial_code' => '1670', 'iso2' => 'MP'],
            ['country_name' => 'Norway', 'dial_code' => '47', 'iso2' => 'NO'],
            ['country_name' => 'Oman', 'dial_code' => '968', 'iso2' => 'OM'],
            ['country_name' => 'Pakistan', 'dial_code' => '92', 'iso2' => 'PK'],
            ['country_name' => 'Palau', 'dial_code' => '680', 'iso2' => 'PW'],
            ['country_name' => 'Palestine', 'dial_code' => '970', 'iso2' => 'PS'],
            ['country_name' => 'Panama', 'dial_code' => '507', 'iso2' => 'PA'],
            ['country_name' => 'Papua New Guinea', 'dial_code' => '675', 'iso2' => 'PG'],
            ['country_name' => 'Paraguay', 'dial_code' => '595', 'iso2' => 'PY'],
            ['country_name' => 'Peru', 'dial_code' => '51', 'iso2' => 'PE'],
            ['country_name' => 'Philippines', 'dial_code' => '63', 'iso2' => 'PH'],
            ['country_name' => 'Pitcairn Islands', 'dial_code' => '649', 'iso2' => 'PN'],
            ['country_name' => 'Poland', 'dial_code' => '48', 'iso2' => 'PL'],
            ['country_name' => 'Portugal', 'dial_code' => '351', 'iso2' => 'PT'],
            ['country_name' => 'Puerto Rico', 'dial_code' => '1787', 'iso2' => 'PR'],
            ['country_name' => 'Qatar', 'dial_code' => '974', 'iso2' => 'QA'],
            ['country_name' => 'Reunion', 'dial_code' => '262', 'iso2' => 'RE'],
            ['country_name' => 'Romania', 'dial_code' => '40', 'iso2' => 'RO'],
            ['country_name' => 'Russia', 'dial_code' => '7', 'iso2' => 'RU'],
            ['country_name' => 'Rwanda', 'dial_code' => '250', 'iso2' => 'RW'],
            ['country_name' => 'Saint Barthelemy', 'dial_code' => '590', 'iso2' => 'BL'],
            ['country_name' => 'Saint Helena', 'dial_code' => '290', 'iso2' => 'SH'],
            ['country_name' => 'Saint Kitts and Nevis', 'dial_code' => '1869', 'iso2' => 'KN'],
            ['country_name' => 'Saint Lucia', 'dial_code' => '1758', 'iso2' => 'LC'],
            ['country_name' => 'Saint Martin', 'dial_code' => '590', 'iso2' => 'MF'],
            ['country_name' => 'Saint Pierre and Miquelon', 'dial_code' => '508', 'iso2' => 'PM'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'dial_code' => '1784', 'iso2' => 'VC'],
            ['country_name' => 'Samoa', 'dial_code' => '685', 'iso2' => 'WS'],
            ['country_name' => 'San Marino', 'dial_code' => '378', 'iso2' => 'SM'],
            ['country_name' => 'Sao Tome and Principe', 'dial_code' => '239', 'iso2' => 'ST'],
            ['country_name' => 'Saudi Arabia', 'dial_code' => '966', 'iso2' => 'SA'],
            ['country_name' => 'Senegal', 'dial_code' => '221', 'iso2' => 'SN'],
            ['country_name' => 'Serbia', 'dial_code' => '381', 'iso2' => 'RS'],
            ['country_name' => 'Seychelles', 'dial_code' => '248', 'iso2' => 'SC'],
            ['country_name' => 'Sierra Leone', 'dial_code' => '232', 'iso2' => 'SL'],
            ['country_name' => 'Singapore', 'dial_code' => '65', 'iso2' => 'SG'],
            ['country_name' => 'Sint Maarten', 'dial_code' => '1721', 'iso2' => 'SX'],
            ['country_name' => 'Slovakia', 'dial_code' => '421', 'iso2' => 'SK'],
            ['country_name' => 'Slovenia', 'dial_code' => '386', 'iso2' => 'SI'],
            ['country_name' => 'Solomon Islands', 'dial_code' => '677', 'iso2' => 'SB'],
            ['country_name' => 'Somalia', 'dial_code' => '252', 'iso2' => 'SO'],
            ['country_name' => 'South Africa', 'dial_code' => '27', 'iso2' => 'ZA'],
            ['country_name' => 'South Korea', 'dial_code' => '82', 'iso2' => 'KR'],
            ['country_name' => 'South Sudan', 'dial_code' => '211', 'iso2' => 'SS'],
            ['country_name' => 'Spain', 'dial_code' => '34', 'iso2' => 'ES'],
            ['country_name' => 'Sri Lanka', 'dial_code' => '94', 'iso2' => 'LK'],
            ['country_name' => 'Sudan', 'dial_code' => '249', 'iso2' => 'SD'],
            ['country_name' => 'Suriname', 'dial_code' => '597', 'iso2' => 'SR'],
            ['country_name' => 'Sweden', 'dial_code' => '46', 'iso2' => 'SE'],
            ['country_name' => 'Switzerland', 'dial_code' => '41', 'iso2' => 'CH'],
            ['country_name' => 'Syria', 'dial_code' => '963', 'iso2' => 'SY'],
            ['country_name' => 'Taiwan', 'dial_code' => '886', 'iso2' => 'TW'],
            ['country_name' => 'Tajikistan', 'dial_code' => '992', 'iso2' => 'TJ'],
            ['country_name' => 'Tanzania', 'dial_code' => '255', 'iso2' => 'TZ'],
            ['country_name' => 'Thailand', 'dial_code' => '66', 'iso2' => 'TH'],
            ['country_name' => 'East Timor', 'dial_code' => '670', 'iso2' => 'TL'],
            ['country_name' => 'Togo', 'dial_code' => '228', 'iso2' => 'TG'],
            ['country_name' => 'Tokelau', 'dial_code' => '690', 'iso2' => 'TK'],
            ['country_name' => 'Tonga', 'dial_code' => '676', 'iso2' => 'TO'],
            ['country_name' => 'Trinidad and Tobago', 'dial_code' => '1868', 'iso2' => 'TT'],
            ['country_name' => 'Tunisia', 'dial_code' => '216', 'iso2' => 'TN'],
            ['country_name' => 'Turkey', 'dial_code' => '90', 'iso2' => 'TR'],
            ['country_name' => 'Turkmenistan', 'dial_code' => '993', 'iso2' => 'TM'],
            ['country_name' => 'Turks and Caicos Islands', 'dial_code' => '1649', 'iso2' => 'TC'],
            ['country_name' => 'Tuvalu', 'dial_code' => '688', 'iso2' => 'TV'],
            ['country_name' => 'Uganda', 'dial_code' => '256', 'iso2' => 'UG'],
            ['country_name' => 'Ukraine', 'dial_code' => '380', 'iso2' => 'UA'],
            ['country_name' => 'United Arab Emirates', 'dial_code' => '971', 'iso2' => 'AE'],
            ['country_name' => 'United Kingdom', 'dial_code' => '44', 'iso2' => 'GB'],
            ['country_name' => 'United States', 'dial_code' => '1', 'iso2' => 'US'],
            ['country_name' => 'Uruguay', 'dial_code' => '598', 'iso2' => 'UY'],
            ['country_name' => 'US Virgin Islands', 'dial_code' => '1340', 'iso2' => 'VI'],
            ['country_name' => 'Uzbekistan', 'dial_code' => '998', 'iso2' => 'UZ'],
            ['country_name' => 'Vanuatu', 'dial_code' => '678', 'iso2' => 'VU'],
            ['country_name' => 'Vatican City', 'dial_code' => '39066', 'iso2' => 'VA'],
            ['country_name' => 'Venezuela', 'dial_code' => '58', 'iso2' => 'VE'],
            ['country_name' => 'Vietnam', 'dial_code' => '84', 'iso2' => 'VN'],
            ['country_name' => 'Wallis and Futuna', 'dial_code' => '681', 'iso2' => 'WF'],
            ['country_name' => 'Yemen', 'dial_code' => '967', 'iso2' => 'YE'],
            ['country_name' => 'Zambia', 'dial_code' => '260', 'iso2' => 'ZM'],
            ['country_name' => 'Zimbabwe', 'dial_code' => '263', 'iso2' => 'ZW'],
        ];

        foreach ($countries as $country) {
            CountryCode::updateOrCreate(
                ['dial_code' => $country['dial_code']],
                $country
            );
        }
    }
}