<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NetworkPrefix;
use Illuminate\Support\Facades\DB;

class NetworkPrefixSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        NetworkPrefix::truncate();

        // Test data for Cambodia network prefixes
        $prefixes = [
            // Cellcard Mobile
            [
                'prefix' => '85592',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85589',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85585',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85517',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85514',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85512',
                'min_length' => 11,
                'max_length' => 12,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            // Smart Mobile (no live coverage)
            [
                'prefix' => '85510',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85516',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85569',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            // Metfone (no live coverage)
            [
                'prefix' => '85597',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85566',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85578',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85561',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85577',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85595',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85599',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85576',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Cellcard Mobile',
                'mcc' => '456',
                'mnc' => '01',
                'live_coverage' => true,
            ],
            [
                'prefix' => '85560',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85567',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85568',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85590',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Metfone',
                'mcc' => '456',
                'mnc' => '08',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85518',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH yes018 Seatel',
                'mcc' => '456',
                'mnc' => '18',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85515',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85570',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85581',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85586',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85587',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85593',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85598',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
            [
                'prefix' => '85596',
                'min_length' => 11,
                'max_length' => 11,
                'country_name' => 'Cambodia',
                'network_name' => 'KH Smart Mobile',
                'mcc' => '456',
                'mnc' => '02',
                'live_coverage' => false,
            ],
        ];

        // Insert the data
        foreach ($prefixes as $prefix) {
            NetworkPrefix::create($prefix);
        }

        $this->command->info('Network prefixes seeded successfully!');
        $this->command->info('Added ' . count($prefixes) . ' Cambodia Cellcard Mobile prefixes');
    }
}